services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db
    ports:
      - "8000:8000"  # FastAPI
      - "3000:3000"  # Dagster
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=tenx_user
      - POSTGRES_PASSWORD=tenx_password
      - POSTGRES_DB=tenx_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
volumes:
  pgdata: